import 'package:auto_route/auto_route.dart';

import 'app_router.gr.dart';

@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  List<AutoRoute> get routes => [
    // Onboarding
    AutoRoute(page: SplashRoute.page, initial: true),
    AutoRoute(page: OnboardRoute.page),
    AutoRoute(page: FingerprintRoute.page),
    AutoRoute(page: SetUpFingerprintRoute.page),
    AutoRoute(page: SettingUpFingerprintRoute.page),
    AutoRoute(page: FingerprintCompleteRoute.page),

    // Auth
    AutoRoute(page: LoginRoute.page),
    AutoRoute(page: SignupRoute.page),
    AutoRoute(page: VerifyPhoneRoute.page),
    AutoRoute(page: VerifyCodeRoute.page),
    AutoRoute(page: VerifyEmailOtpRoute.page),
    AutoRoute(page: CreatePasswordRoute.page),
    AutoRoute(page: CreatePinRoute.page),
    AutoRoute(page: CreatedPinRoute.page),
    AutoRoute(page: ForgotPasswordRoute.page),
    AutoRoute(page: VerifyForgotRoute.page),
    AutoRoute(page: PasswordChangedRoute.page),
    AutoRoute(page: LoginPasswordResetRoute.page),
    AutoRoute(page: LoginPasswordChangedRoute.page),

    // Dashboard
    AutoRoute(page: ExploreRoute.page),
    AutoRoute(page: HomeRoute.page),
    AutoRoute(page: FeaturesRoute.page),
    AutoRoute(page: NotificationRoute.page),

    // KYC
    AutoRoute(page: KycVerificationRoute.page),
    AutoRoute(page: BvnVerificationRoute.page),
    AutoRoute(page: BvnconfirmRoute.page),
    AutoRoute(page: BvnFaceRecogRoute.page),
    AutoRoute(page: KycFaceVerificationRoute.page),
    AutoRoute(page: ReviewDocumentRoute.page),
    AutoRoute(page: KycVerificationCompleteRoute.page),

    // Transaction
    AutoRoute(page: TransactionHistoryRoute.page),
    AutoRoute(page: TransactionHistoryDetailRoute.page),
    AutoRoute(page: FundWalletRoute.page),
    AutoRoute(page: TransferFundsRoute.page),
    AutoRoute(page: AmountAndInfoRoute.page),
    AutoRoute(page: ConfirmTransactionRoute.page),
    AutoRoute(page: ReceiptRoute.page),
    AutoRoute(page: TransactionSuccessfulRoute.page),

    // Bills
    AutoRoute(page: BillsRoute.page),
    AutoRoute(page: AirtimeRoute.page),
    AutoRoute(page: AirtimeConfirmRoute.page),
    AutoRoute(page: AirtimeReceiptRoute.page),
    AutoRoute(page: DataRoute.page),
    AutoRoute(page: DataConfirmRoute.page),
    AutoRoute(page: DataReceiptRoute.page),
    AutoRoute(page: BetRoute.page),
    AutoRoute(page: BetConfirmRoute.page),
    AutoRoute(page: BettingReceiptRoute.page),
    AutoRoute(page: ElectricityRoute.page),
    AutoRoute(page: ElectricityConfirmRoute.page),
    AutoRoute(page: ElectricityReceiptRoute.page),
    AutoRoute(page: TvCableRoute.page),
    AutoRoute(page: TvCableConfirmRoute.page),
    AutoRoute(page: TvCableReceiptRoute.page),
    AutoRoute(page: PaymentRoute.page),
    AutoRoute(page: BillConfirmRoute.page),
    AutoRoute(page: BillSuccessRoute.page),
    AutoRoute(page: BillReceiptRoute.page),

    // Crypto
    AutoRoute(page: CryptoRoute.page),
    AutoRoute(page: AllTokensRoute.page),
    AutoRoute(page: TokenDetailRoute.page),
    AutoRoute(page: WatchlistRoute.page),
    AutoRoute(page: AssetsRoute.page),
    AutoRoute(page: YourAssetsRoute.page),
    AutoRoute(page: SelectAssetRoute.page),
    AutoRoute(page: FetchWalletProgressRoute.page),
    AutoRoute(page: CryptoTransactionRoute.page),
    AutoRoute(page: ConfirmBuyRoute.page),
    AutoRoute(page: ConfirmSellRoute.page),
    AutoRoute(page: ManageAssetsRoute.page),
    AutoRoute(page: BuyCryptoRoute.page),
    AutoRoute(page: CryptoReceiptRoute.page),
    AutoRoute(page: CryptoTransactionSuccessfulRoute.page),
    AutoRoute(page: SellCryptoRoute.page),
    AutoRoute(page: CryptoSellReceiptRoute.page),
    AutoRoute(page: CryptoSellSuccessfulRoute.page),
    AutoRoute(page: ReceiveCryptoRoute.page),
    AutoRoute(page: CryptoTransactionsHistoryRoute.page),
    AutoRoute(page: CryptoTransactionsDetailRoute.page),

    // Gift Card
    AutoRoute(page: GiftcardRoute.page),
    AutoRoute(page: BuyGiftcardRoute.page),
    AutoRoute(page: BuyGiftCardFeaturesRoute.page),
    AutoRoute(page: GiftCardBuyReceiptRoute.page),
    AutoRoute(page: GiftCardSuccessRoute.page),
    AutoRoute(page: SellGiftcardRoute.page),
    AutoRoute(page: SellGiftCardFeaturesRoute.page),
    AutoRoute(page: ConfirmGiftCardSellRoute.page),
    AutoRoute(page: GiftcardSellReceiptRoute.page),
    AutoRoute(page: SellGiftCardSuccessRoute.page),

    // Virtual Card
    AutoRoute(page: VirtualCardRoute.page),
    AutoRoute(page: MyCardsRoute.page),
    AutoRoute(page: CardRoute.page),
    AutoRoute(page: AddDollarCardRoute.page),
    AutoRoute(page: CreateVirtualCardRoute.page),
    AutoRoute(page: VirtualCardSuccessRoute.page),
    AutoRoute(page: CardTransactionRoute.page),
    AutoRoute(page: TransactionDetailsRoute.page),
    AutoRoute(page: FundCardRoute.page),
    AutoRoute(page: FundCardReceiptRoute.page),
    AutoRoute(page: FundCardSuccessfulRoute.page),
    AutoRoute(page: CardLimitRoute.page),
    AutoRoute(page: SearchCardRoute.page),

    // Flight
    AutoRoute(page: FlightBookingRoute.page),
    AutoRoute(page: OneWayTripRoute.page),
    AutoRoute(page: RoundWayTripRoute.page),
    AutoRoute(page: MultiTripRoute.page),
    AutoRoute(page: SearchResultRoute.page),
    AutoRoute(page: SearchResultTwoRoute.page),
    AutoRoute(page: MultiSearchResultRoute.page),
    AutoRoute(page: FlightDetailsRoute.page),
    AutoRoute(page: FlightDetailsTwoRoute.page),
    AutoRoute(page: MultiFlightDetailsRoute.page),
    AutoRoute(page: PassengerDetailsRoute.page),
    AutoRoute(page: PassengerDetailsTwoRoute.page),
    AutoRoute(page: MultiPassengersDetailsRoute.page),
    AutoRoute(page: SelectSeatRoute.page),
    AutoRoute(page: SelectInboundSeatRoute.page),
    AutoRoute(page: SelectOutboundSeatRoute.page),
    AutoRoute(page: MultiSelectSeatOneRoute.page),
    AutoRoute(page: MultiSelectSeatTwoRoute.page),
    AutoRoute(page: MultiSelectSeatThreeRoute.page),
    AutoRoute(page: BaggageRoute.page),
    AutoRoute(page: FlightPaymentRoute.page),
    AutoRoute(page: FlightTwoPaymentRoute.page),
    AutoRoute(page: MultiPaymentRoute.page),
    AutoRoute(page: FlightPaymentReceiptRoute.page),
    AutoRoute(page: FlightTwoPaymentReceiptRoute.page),
    AutoRoute(page: MultiPaymentReceiptRoute.page),
    AutoRoute(page: FlightPaymentSuccessRoute.page),
    AutoRoute(page: FlightTwoPaymentSuccessRoute.page),
    AutoRoute(page: MultiPaymentSuccessRoute.page),
    AutoRoute(page: FlightBookRoute.page),
    AutoRoute(page: FlightCardRoute.page),
    AutoRoute(page: BookedFlightsRoute.page),
    AutoRoute(page: ActiveFlightRoute.page),
    AutoRoute(page: BoardingPassRoute.page),
    AutoRoute(page: BoardingPassDetailsRoute.page),
    AutoRoute(page: BookingPoliciesRoute.page),
    AutoRoute(page: RefundPolicyRoute.page),
    AutoRoute(page: RefundDetailsRoute.page),
    AutoRoute(page: CancelFlightRoute.page),
    AutoRoute(page: CancelFlightSuccessfulRoute.page),

    // Shopping
    AutoRoute(page: ShoppingRoute.page),
    AutoRoute(page: ClothsRoute.page),
    AutoRoute(page: ClothsDetailsRoute.page),
    AutoRoute(page: CheckOutRoute.page),
    AutoRoute(page: OrderReceiptRoute.page),
    AutoRoute(page: OrderSuccessfulRoute.page),
    AutoRoute(page: YourOrderRoute.page),
    AutoRoute(page: TrackOrderRoute.page),

    // Settings
    AutoRoute(page: SettingsRoute.page),
    AutoRoute(page: ProfileRoute.page),
    AutoRoute(page: EditProfileRoute.page),
    AutoRoute(page: EditAccountRoute.page),
    AutoRoute(page: BankAccountRoute.page),
    AutoRoute(page: ChangePasswordRoute.page),
    AutoRoute(page: VerifyPasswordDetailRoute.page),
    AutoRoute(page: PinResetRoute.page),
    AutoRoute(page: PinResetCompleteRoute.page),
    AutoRoute(page: TransactionLimitRoute.page),
    AutoRoute(page: HelpAndSupportRoute.page),
    AutoRoute(page: FaqTabRoute.page),
    AutoRoute(page: ContactTabRoute.page),
    AutoRoute(page: PrivacyRoute.page),
    AutoRoute(page: TermsAndConditionRoute.page),
    AutoRoute(page: ReferRoute.page),
  ];
}
